### ISSUE TITLE
Database Restructure

### ISSUE THREAD

**Issue by DallasEpperson** [smeans/makermon#2]
The database needs to be restructured a bit to facilitate multiple permissioned items. While we're at it, we might as well preemptively add columns for a future audit log update.

One schema proposal could be:
  
* member
  * Primary Key `int`
  * emailPrefix (tied to @colamakerspace.com account) `varchar`
  * startDate `datetime`
  * validUntil `datetime`
  
* rfidToken
  * primaryKey `int`
  * token `varchar` (this is what's stored on the card)
  * memberId `foreign key` `int`
  * enabled `boolean`
  
* item
  * primary key `int`
  * description `varchar`
  * enabled `boolean`
  * disabledReason `varchar`
  
* training
  * primary key `int`
  * description `varchar`
  * validForDays `int`

* requiredTraining
  * primary key `int`
  * trainingId `foreign key` `int`
  * itemId `foreign key` `int`
  
* completedTraining
  * primary key `int`
  * trainingId `foreign key` `int`
  * memberId `foreign key` `int`
  * completedDate `datetime`
  * expirationDate `datetime`

**Comment by steven6282** [comment]
This issue is assumed resolved with #11
